# Generated by Django 3.2.8 on 2023-03-31 07:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_chapter',
            fields=[
                ('chapter_id', models.AutoField(primary_key=True, serialize=False)),
                ('chapter_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('city_shortform', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('course_fees', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='tbl_firstreceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField(default=0)),
                ('discountedfees', models.FloatField(default=0)),
                ('deposit', models.FloatField(default=0)),
                ('balance', models.FloatField(default=0)),
                ('discount', models.FloatField(default=0)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('date_updated', models.DateField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imsApp.tbl_course')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_referenceby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referenceby_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_remisier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remisier_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_state',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=100)),
                ('state_shortform', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_studenttype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studenttype', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('student_emailid', models.EmailField(max_length=254)),
                ('student_contactno', models.BigIntegerField()),
                ('student_whatsappno', models.BigIntegerField()),
                ('student_gender', models.CharField(max_length=6)),
                ('student_dateofbirth', models.DateField()),
                ('student_address', models.CharField(max_length=100)),
                ('student_pincode', models.IntegerField()),
                ('modeofcourse', models.CharField(max_length=10)),
                ('student_occupation', models.CharField(max_length=100)),
                ('reference_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imsApp.tbl_referenceby')),
                ('student_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imsApp.tbl_city')),
                ('student_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imsApp.tbl_course')),
                ('student_qualification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imsApp.tbl_qualification')),
                ('student_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imsApp.tbl_state')),
                ('student_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imsApp.tbl_studenttype')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_session',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_name', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='doc/')),
                ('chapter_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imsApp.tbl_chapter')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_secondreceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discountedfees', models.FloatField(default=0)),
                ('deposit', models.FloatField(default=0)),
                ('balance', models.FloatField(default=0)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('date_updated', models.DateField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imsApp.tbl_course')),
                ('firstreceipt', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='imsApp.tbl_firstreceipt')),
                ('student_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imsApp.tbl_student')),
            ],
        ),
        migrations.AddField(
            model_name='tbl_firstreceipt',
            name='student_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imsApp.tbl_student'),
        ),
        migrations.CreateModel(
            name='tbl_exfeesdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_date', models.DateField(default=django.utils.timezone.now)),
                ('paying_date', models.DateField()),
                ('remark', models.CharField(max_length=200)),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imsApp.tbl_student')),
                ('pending_amt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imsApp.tbl_firstreceipt')),
            ],
        ),
        migrations.AddField(
            model_name='tbl_city',
            name='state_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imsApp.tbl_state'),
        ),
        migrations.AddField(
            model_name='tbl_chapter',
            name='course_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imsApp.tbl_course'),
        ),
    ]
